# Generated by Django 3.2.9 on 2021-12-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_alter_asset_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='plate_number',
            field=models.CharField(max_length=100),
        ),
    ]
