# Generated by Django 3.2.9 on 2021-12-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_alter_asset_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_availabe',
            field=models.BooleanField(default=True),
        ),
    ]
