# Generated by Django 3.2.9 on 2021-12-29 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0004_asset_is_availabe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='asset_management.asset', verbose_name='asset')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_asset', to=settings.AUTH_USER_MODEL, verbose_name='employee_asset')),
            ],
        ),
    ]
