# Generated by Django 3.2.9 on 2021-12-29 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0006_rename_is_availabe_asset_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassign',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset', to='asset_management.asset', verbose_name='asset'),
        ),
        migrations.AlterField(
            model_name='assetassign',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_asset', to=settings.AUTH_USER_MODEL, verbose_name='employee_asset'),
        ),
    ]
