# Generated by Django 3.2.9 on 2022-01-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=256)),
                ('log_url', models.CharField(max_length=150)),
                ('log_model', models.CharField(max_length=100)),
            ],
        ),
    ]
