# Generated by Django 3.2.9 on 2022-01-21 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_applog'),
    ]

    operations = [
        migrations.AddField(
            model_name='applog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applog',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applog',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applog',
            name='log_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applog',
            name='log_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='applog',
            name='log_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
