# Generated by Django 3.2.9 on 2021-12-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee', serialize=False, to='auth.user', verbose_name='employee')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/employee')),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='images/employee_document')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('driving_license', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
            options={
                'db_table': 'employee_profile',
            },
        ),
    ]
