# Generated by Django 3.2.9 on 2021-12-29 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_employeeloginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_login_logs', to=settings.AUTH_USER_MODEL, verbose_name='employee_login_logs'),
        ),
    ]
