# Generated by Django 3.2.9 on 2021-12-30 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_employeeloginlog_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='etlog', to=settings.AUTH_USER_MODEL, verbose_name='etlog')),
            ],
        ),
    ]
