# Generated by Django 3.2.9 on 2021-12-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_etlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloginlog',
            name='logout_cause',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
