# Generated by Django 3.2.9 on 2022-01-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0007_auto_20211229_1225'),
        ('accounts', '0005_employeeloginlog_logout_cause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlog',
            name='long',
        ),
        migrations.AddField(
            model_name='etlog',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etlog_asset', to='asset_management.asset', verbose_name='etlog_asset'),
        ),
        migrations.AddField(
            model_name='etlog',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='etlog',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('Job Assigned', 'Job Assigned')], default='Idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='etlog',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
    ]
