# Generated by Django 3.2.9 on 2022-01-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220105_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='security_license',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
