# Generated by Django 3.2.9 on 2022-01-13 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0007_auto_20211229_1225'),
        ('accounts', '0007_employeeprofile_security_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_login_logs', to=settings.AUTH_USER_MODEL, verbose_name='employee_login_logs'),
        ),
        migrations.AlterField(
            model_name='etlog',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etlog_asset', to='asset_management.asset', verbose_name='etlog_asset'),
        ),
        migrations.AlterField(
            model_name='etlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etlog', to=settings.AUTH_USER_MODEL, verbose_name='etlog'),
        ),
    ]
