# Generated by Django 3.2.9 on 2022-01-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220113_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlog',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('job_assigned', 'job_assigned')], default='idle', max_length=20),
        ),
    ]
