# Generated by Django 3.2.9 on 2022-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_etlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlog',
            name='login_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
