# Generated by Django 3.2.9 on 2022-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_etlog_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('job_assigned', 'job_assigned'), ('inactive', 'inactive')], default='inactive', max_length=20),
        ),
    ]
