# Generated by Django 3.2.9 on 2021-12-30 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_phone_number', models.CharField(blank=True, max_length=15)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('Cancelled', 'Cancelled'), ('Transferred', 'Transferred'), ('Completed', 'Completed')], default='Created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employeejob', to=settings.AUTH_USER_MODEL, verbose_name='employeejob')),
            ],
        ),
    ]
