# Generated by Django 3.2.9 on 2022-01-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0002_auto_20211230_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remark',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
