# Generated by Django 3.2.9 on 2022-01-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0003_job_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='job_no',
        ),
    ]
