# Generated by Django 3.2.9 on 2022-01-11 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_management', '0005_job_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_job_request', to=settings.AUTH_USER_MODEL, verbose_name='employee_job_request')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_request', to='job_management.job', verbose_name='job_request')),
            ],
        ),
    ]
