# Generated by Django 3.2.9 on 2022-01-12 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_management', '0007_jobrequest_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_note', models.TextField(blank=True, max_length=500)),
                ('time_on', models.DateTimeField()),
                ('time_off', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_job_report', to=settings.AUTH_USER_MODEL, verbose_name='employee_job_report')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_report', to='job_management.job', verbose_name='job_report')),
            ],
        ),
        migrations.CreateModel(
            name='JobReportImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='images/job_report_images/')),
                ('job_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_management.jobreport')),
            ],
        ),
    ]
