# Generated by Django 3.2.9 on 2022-01-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0008_jobreport_jobreportimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobReportImages',
            new_name='JobReportImage',
        ),
    ]
