# Generated by Django 3.2.9 on 2022-01-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0009_rename_jobreportimages_jobreportimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='long',
            new_name='lng',
        ),
    ]
