# Generated by Django 3.2.9 on 2022-01-13 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_management', '0012_alter_jobassign_transfered_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassign',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_job', to=settings.AUTH_USER_MODEL, verbose_name='employee_job'),
        ),
        migrations.AlterField(
            model_name='jobassign',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assign', to='job_management.job', verbose_name='job_assign'),
        ),
        migrations.AlterField(
            model_name='jobassign',
            name='transfered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_transferred_from', to=settings.AUTH_USER_MODEL, verbose_name='job_transferred_from'),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_job_report', to=settings.AUTH_USER_MODEL, verbose_name='employee_job_report'),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_report', to='job_management.job', verbose_name='job_report'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_job_request', to=settings.AUTH_USER_MODEL, verbose_name='employee_job_request'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_request', to='job_management.job', verbose_name='job_request'),
        ),
    ]
