# Generated by Django 3.2.9 on 2022-01-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0015_alter_jobreport_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreport',
            name='bureu',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
