# Generated by Django 3.2.9 on 2022-02-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0016_jobreport_bureu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreportimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/job_report_images/'),
        ),
    ]
